import type { CategoryDTO, ProductDTO } from "./types";

/**
 * Catálogo de demostración.
 *
 * Cumple dos funciones:
 *  1. Es la fuente que usa `npm run db:seed` para poblar Neon.
 *  2. Es el fallback cuando `DATABASE_URL` todavía no está configurada,
 *     para que la web se pueda ver desde el primer `npm run dev`.
 */

const TALLAS_NINOS = [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33];
const TALLAS_BEBES = [17, 18, 19, 20, 21, 22];

export const demoCategories: CategoryDTO[] = [
  {
    id: 1,
    slug: "todos",
    name: "TODOS",
    subtitle: "LOS TENIS",
    icon: "🦖",
    image: "/categorias/cat-todos.webp",
    accent: "green",
    inNav: false,
    sortOrder: 0,
  },
  {
    id: 2,
    slug: "ninos",
    name: "NIÑOS",
    subtitle: "3 - 12 AÑOS",
    icon: "🦕",
    image: "/categorias/cat-ninos.webp",
    accent: "blue",
    inNav: true,
    sortOrder: 1,
  },
  {
    id: 3,
    slug: "ninas",
    name: "NIÑAS",
    subtitle: "3 - 12 AÑOS",
    icon: "🦖",
    image: "/categorias/cat-ninas.webp",
    accent: "pink",
    inNav: true,
    sortOrder: 2,
  },
  {
    id: 4,
    slug: "bebes",
    name: "BEBÉS",
    subtitle: "0 - 3 AÑOS",
    icon: "🥚",
    image: "/categorias/cat-bebes.webp",
    accent: "yellow",
    inNav: true,
    sortOrder: 3,
  },
  {
    id: 5,
    slug: "colecciones",
    name: "COLECCIONES",
    subtitle: "ESPECIALES",
    icon: "🪺",
    image: "/categorias/cat-colecciones.webp",
    accent: "purple",
    inNav: true,
    sortOrder: 4,
  },
  {
    id: 6,
    slug: "ofertas",
    name: "OFERTAS",
    subtitle: "IMPERDIBLES",
    icon: "%",
    image: "/categorias/cat-ofertas.webp",
    accent: "orange",
    inNav: true,
    sortOrder: 5,
  },
];

export const demoProducts: ProductDTO[] = [
  {
    id: 1,
    slug: "dino-rex-verde",
    name: "DINO REX VERDE",
    description:
      "Tenis con forma de dinosaurio, luces LED en la suela y cierre de velcro para que los pequeños exploradores se los pongan solos.",
    price: 190,
    compareAtPrice: null,
    categorySlug: "ninos",
    sizes: TALLAS_NINOS,
    images: ["/productos/dino-rex-verde.webp"],
    emoji: "🦖",
    color: "Verde",
    stock: 24,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 2,
    slug: "triceratops-azul",
    name: "TRICERATOPS AZUL",
    description:
      "Diseño de triceratops con cuernos acolchados, suela antideslizante y luces que se encienden con cada paso.",
    price: 190,
    compareAtPrice: null,
    categorySlug: "ninos",
    sizes: TALLAS_NINOS,
    images: ["/productos/triceratops-azul.webp"],
    emoji: "🦕",
    color: "Azul",
    stock: 18,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 3,
    slug: "t-rex-rojo",
    name: "T-REX ROJO",
    description:
      "El más feroz de la manada: escamas texturizadas, dientes en relieve y luces rojas que dejan huella.",
    price: 190,
    compareAtPrice: null,
    categorySlug: "ninos",
    sizes: TALLAS_NINOS,
    images: ["/productos/t-rex-rojo.webp"],
    emoji: "🦖",
    color: "Rojo",
    stock: 12,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 4,
    slug: "stego-marron",
    name: "STEGO MARRÓN",
    description:
      "Estegosaurio con placas dorsales de goma flexible. Material resistente para el uso diario.",
    price: 190,
    compareAtPrice: null,
    categorySlug: "ninos",
    sizes: TALLAS_NINOS,
    images: ["/productos/stego-marron.webp"],
    emoji: "🦕",
    color: "Marrón",
    stock: 15,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 5,
    slug: "dino-rosa-brillante",
    name: "DINO ROSA BRILLANTE",
    description:
      "Escamas con destellos y luces rosadas. Pensado para las exploradoras más aventureras.",
    price: 195,
    compareAtPrice: 230,
    categorySlug: "ninas",
    sizes: TALLAS_NINOS,
    images: ["/productos/dino-rosa-brillante.webp"],
    emoji: "🦖",
    color: "Rosa",
    stock: 20,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 6,
    slug: "pteroluz-violeta",
    name: "PTEROLUZ VIOLETA",
    description:
      "Pterodáctilo con alas laterales de goma y luces violetas. Ligerísimo y muy cómodo.",
    price: 199,
    compareAtPrice: null,
    categorySlug: "ninas",
    sizes: TALLAS_NINOS,
    images: ["/productos/pteroluz-violeta.webp"],
    emoji: "🦅",
    color: "Violeta",
    stock: 9,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 7,
    slug: "bebe-huevito-amarillo",
    name: "BEBÉ HUEVITO AMARILLO",
    description:
      "Primeros pasos con suela flexible, sin luces y con interior acolchado. Ideal de 0 a 3 años.",
    price: 150,
    compareAtPrice: null,
    categorySlug: "bebes",
    sizes: TALLAS_BEBES,
    images: ["/productos/bebe-huevito-amarillo.webp"],
    emoji: "🥚",
    color: "Amarillo",
    stock: 30,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 8,
    slug: "raptor-naranja",
    name: "RAPTOR NARANJA",
    description:
      "Velociraptor con garras decorativas y refuerzo en la punta. Aguanta la selva del recreo.",
    price: 175,
    compareAtPrice: 210,
    categorySlug: "ofertas",
    sizes: TALLAS_NINOS,
    images: ["/productos/raptor-naranja.webp"],
    emoji: "🦖",
    color: "Naranja",
    stock: 7,
    isNew: false,
    isFeatured: true,
  },
];
